Update msrest dependency for azure-sdk-for-python support
requirements.txt
azure-eventgrid>=4.0.0
botbuilder-integration-aiohttp>=4.14.0

ERROR: Cannot install -r requirements.txt (line 1) and botbuilder-schema==4.14.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    azure-eventgrid 4.0.0 depends on msrest>=0.6.19
    botbuilder-schema 4.14.0 depends on msrest==0.6.10